In [8]:
print("Hello World!")

Hello World!


In [9]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
import numpy as np
my_list=[1,2,3,4,5,6,7]
arr=np.array(my_list)
print(type(arr))
print(arr)
arr.shape

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


(7,)

In [21]:
import numpy as np
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[3,4,5,6,7]
arr=np.array([my_list1,my_list2,my_list3])
print(type(arr))
print(arr)
arr.shape
arr.reshape(5,3)
arr.shape


<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


(3, 5)

In [22]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[3,4,5,6,7]
arr=np.array([my_list1,my_list2,my_list3])
print(type(arr))
print(arr)
arr.shape
arr.reshape(5,3)
arr.shape

<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


(3, 5)

In [28]:
print(arr)
arr[1:,2:4]
arr[1:2,1:4]

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


array([[3, 4, 5]])

In [32]:
arr=np.arange(0,10)
print(arr)
arr

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])